# Generated by Django 4.1.3 on 2022-12-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_banner_http_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='CategoryImage')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.category')),
            ],
        ),
    ]
