# Generated by Django 4.1.3 on 2022-12-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_porduct_discount_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porduct',
            new_name='Product',
        ),
    ]
