# Generated by Django 4.1.3 on 2022-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_rename_products_order_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('SSL Commerz', 'SSL Commerz')], max_length=100, null=True),
        ),
    ]
