# Generated by Django 4.1.3 on 2022-12-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_rename_shippingaddress_shipingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipingaddress',
            old_name='order_nite',
            new_name='order_note',
        ),
    ]
